name: E2E Tests

on: [push]

jobs:
  e2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn
    - name: E2E Tests
      run: gulp e2e --retries=3
